<?php

return [
    'coming_soon' => true,
    'summary' => 'Vintage Story servers in the US and Germany. Coming soon.',
    'tagline' => 'Affordable and friendly but limited hosting.',
    'regions' => [
        ['code' => 'us', 'label' => 'United States', 'flag' => 'US', 'lat' => 39.5, 'lng' => -98.35],
        ['code' => 'eu-de', 'label' => 'Europe (Germany)', 'flag' => 'DE', 'lat' => 51.16, 'lng' => 10.45],
    ],
    // Sellable capacity per region and plan. Tune in private deploy config if needed.
    'stock' => [
        'us' => [
            'friends' => 4,
            'modded' => 3,
            'heavy' => 1,
        ],
        'eu-de' => [
            'friends' => 4,
            'modded' => 3,
            'heavy' => 1,
        ],
    ],
    'hardware' => [
        'cpu' => 'AMD EPYC 4344P',
        'cpu_detail' => '8 cores / 16 threads, up to 5.3 GHz',
        'memory' => 'DDR5 ECC',
        'storage' => 'NVMe SSD',
    ],
    'features' => [
        ['icon' => 'archive', 'text' => 'Automated backups'],
        ['icon' => 'cog', 'text' => 'Mod browser with one-click installs'],
        ['icon' => 'file-code', 'text' => 'File browser and editor'],
        ['icon' => 'package', 'text' => 'Unlimited mods'],
        ['icon' => 'users', 'text' => 'Player count limited by RAM and CPU, not an artificial slot cap'],
        ['icon' => 'globe', 'text' => 'US and Germany locations'],
        ['icon' => 'container', 'text' => 'Easy migration to your own servers to self-host (Docker)'],
        ['icon' => 'badge-check', 'text' => 'No lock-in or hidden fees'],
        ['icon' => 'leaf', 'text' => 'Quality servers with efficient, lower-waste hosting'],
        ['icon' => 'upload', 'text' => 'SFTP and HTTP file uploads'],
    ],
    'home_highlights' => [
        [
            'icon' => 'badge-check',
            'title' => 'Consumer friendly',
            'text' => 'Fair prices, a clear refund policy, and an easy path to migrate off.',
        ],
        [
            'icon' => 'users',
            'title' => 'Unlimited slots',
            'text' => 'Player count follows your plan hardware. No fake slot caps.',
        ],
        [
            'icon' => 'package',
            'title' => 'One-click mods',
            'text' => 'Install from VS ModDB in one click. Add as many as your storage allows.',
            'link' => [
                'label' => 'VS ModDB',
                'href' => 'https://mods.vintagestory.at/',
                'external' => true,
            ],
        ],
        [
            'icon' => 'file-code',
            'title' => 'File browser and editor',
            'text' => 'Browse and edit server files from the panel.',
        ],
        [
            'icon' => 'archive',
            'title' => 'Automatic and manual backups',
            'text' => 'Scheduled backups, plus backup now when you need it.',
        ],
        [
            'icon' => 'globe',
            'title' => 'US and EU',
            'text' => 'Servers in the United States and Germany.',
        ],
    ],
    'home_note' => 'Limited availability when we open. First come, first served.',
    'plans' => [
        [
            'slug' => 'friends',
            'name' => 'Friends',
            'flavor' => 'Ember',
            'price_monthly' => 10,
            'price_yearly' => 100,
            'yearly_savings' => 20,
            'ram_gb' => 4,
            'storage_gb' => 25,
            'comfort' => 'Good for a small group on light or vanilla play',
            'blurb' => 'A small world with friends. Light mods, not a huge pack.',
            'recommended' => false,
        ],
        [
            'slug' => 'modded',
            'name' => 'Modded',
            'flavor' => 'Forge',
            'price_monthly' => 15,
            'price_yearly' => 150,
            'yearly_savings' => 30,
            'ram_gb' => 8,
            'storage_gb' => 50,
            'comfort' => 'Good for normal ModDB packs and growing worlds',
            'blurb' => 'The usual pick for modded Vintage Story.',
            'recommended' => true,
        ],
        [
            'slug' => 'heavy',
            'name' => 'Heavy',
            'flavor' => 'Crucible',
            'price_monthly' => 25,
            'price_yearly' => 250,
            'yearly_savings' => 50,
            'ram_gb' => 16,
            'storage_gb' => 100,
            'comfort' => 'For big packs and busier worlds',
            'blurb' => 'More RAM when the mod list and player load get thick.',
            'recommended' => false,
        ],
    ],
    'refund' => [
        'intro' => 'We would rather refund a bad fit than keep the money. Export your world before you cancel if you want to keep it.',
        'points' => [
            'Monthly plans: full refund within 7 days',
            'Annual plans: full refund within 14 days. After that, unused whole months in year one are refunded at the monthly rate',
            'Refunds go back to the original payment method',
            'Cancel anytime. Service ends at the paid period unless you ask to shut down sooner',
            'Refund abuse can close refunds on that account',
        ],
    ],
    'notes' => [
        'Prices are USD. EUR follows the ECB rate and updates about every six hours',
        'Annual billing saves two months versus monthly',
        'Export your world and mods anytime, including a Docker setup for self-hosting',
    ],
    'change_note' => 'Features and plans are subject to change until we are open.',
    'exchange' => [
        'cache_seconds' => (int) env('SMELTERWORKS_EXCHANGE_CACHE_SECONDS', 21600),
        'stale_seconds' => (int) env('SMELTERWORKS_EXCHANGE_STALE_SECONDS', 604800),
        'fallback_usd_to_eur' => (float) env('SMELTERWORKS_EXCHANGE_FALLBACK_USD_TO_EUR', 0.92),
    ],
];
