<?php

return [
    'preview_label' => 'Interactive preview',
    'disclaimer' => 'Simulated panel. Nothing here provisions servers or changes real files.',
    'mods_api' => '/panel/demo/mods',
    'exit_url' => '/hosting',
    'user' => [
        'name' => 'Alex',
        'email' => 'alex@northwind.example',
        'organization' => 'Northwind Vintage',
        'role' => 'Owner',
        'timezone' => 'America/Chicago',
    ],
    'nav' => [
        ['id' => 'dashboard', 'label' => 'Dashboard', 'icon' => 'layers'],
        ['id' => 'server', 'label' => 'Server', 'icon' => 'container'],
        ['id' => 'mods', 'label' => 'Mod browser', 'icon' => 'package'],
        ['id' => 'pairing', 'label' => 'Pairing', 'icon' => 'key-round'],
        ['id' => 'profile', 'label' => 'Profile', 'icon' => 'user'],
        ['id' => 'settings', 'label' => 'Settings', 'icon' => 'settings'],
    ],
    'features' => [
        ['icon' => 'archive', 'label' => 'Automatic and manual backups'],
        ['icon' => 'file-code', 'label' => 'File browser, editor, SFTP uploads'],
        ['icon' => 'container', 'label' => 'One-click migration between cloud and paired hardware'],
        ['icon' => 'globe', 'label' => 'US and Germany cloud regions'],
        ['icon' => 'upload', 'label' => 'HTTP uploads for quick mod drops'],
        ['icon' => 'badge-check', 'label' => 'Relic Launcher server list and migration hooks'],
    ],
    'settings' => [
        ['id' => 'email_alerts', 'label' => 'Email alerts for crashes and failed backups', 'enabled' => true],
        ['id' => 'console_timestamps', 'label' => 'Show timestamps in console', 'enabled' => true],
        ['id' => 'auto_restart', 'label' => 'Auto-restart after crash', 'enabled' => false],
        ['id' => 'dark_console', 'label' => 'High-contrast console', 'enabled' => true],
        ['id' => 'confirm_power', 'label' => 'Confirm stop and restart', 'enabled' => false],
    ],
    'servers' => [
        [
            'id' => 'ember-hollow',
            'name' => 'Ember Hollow',
            'type' => 'Cloud',
            'region' => 'United States',
            'plan' => 'Forge',
            'status' => 'running',
            'players' => '4 / 12',
            'ram' => '6.2 GB / 8 GB',
            'storage' => '31 GB / 50 GB NVMe',
            'address' => 'ember-hollow.us.smelt.example',
            'highlights' => [
                'Managed Vintage Story container',
                'Daily backups to NVMe',
                'Optional cloud backup tier',
                'Docker export any time',
            ],
        ],
        [
            'id' => 'ruins-eu',
            'name' => 'Ruins EU',
            'type' => 'Cloud',
            'region' => 'Germany',
            'plan' => 'Heavy',
            'status' => 'stopped',
            'players' => '0 / 20',
            'ram' => '0 GB / 16 GB',
            'storage' => '78 GB / 100 GB NVMe',
            'address' => 'ruins-eu.de.smelt.example',
            'highlights' => [
                'Managed Vintage Story container',
                'Daily backups to NVMe',
                'Heavy RAM for large mod packs',
                'Germany region latency',
            ],
        ],
        [
            'id' => 'home-forge',
            'name' => 'Home Forge',
            'type' => 'Paired',
            'region' => 'Your hardware',
            'plan' => 'Anchor',
            'status' => 'running',
            'players' => '2 / 8',
            'ram' => '5.1 GB / 16 GB',
            'storage' => 'Local disk',
            'address' => '192.168.1.40:42420',
            'daemon' => 'basement-box',
            'highlights' => [
                'Panel manages smelterd on your box',
                'Local backups on host disk included',
                'Optional S3-compatible cloud backups',
                'daemon-tool works when the panel is offline',
            ],
        ],
    ],
    'paired' => [
        ['name' => 'basement-box', 'status' => 'online', 'last_seen' => '2 minutes ago', 'servers' => 1],
        ['name' => 'vps-fallback', 'status' => 'offline', 'last_seen' => '3 days ago', 'servers' => 0],
    ],
    'installed_mods' => [
        [
            'modid' => 'primitivesurvival',
            'name' => 'Primitive Survival',
            'author' => 'SpearAndFang',
            'version' => '3.2.1',
            'enabled' => true,
            'logo' => 'https://moddbcdn.vintagestory.at/logo3_dd03713f749ef0cf43fa5a03bf7991fa.png',
        ],
        [
            'modid' => 'wildcrafttrees',
            'name' => 'Wildcraft Trees',
            'author' => 'gabb',
            'version' => '1.4.0',
            'enabled' => true,
            'logo' => null,
        ],
        [
            'modid' => 'betterruins',
            'name' => 'BetterRuins',
            'author' => 'NiclAss',
            'version' => '0.5.8',
            'enabled' => false,
            'update' => '0.5.9',
            'logo' => 'https://moddbcdn.vintagestory.at/BetterRuinsmoddbicon_021a6a8838be7058c2ab618ce0097224_480_320.png',
        ],
    ],
    'backups' => [
        ['label' => 'Daily auto', 'when' => 'Today, 04:00 UTC', 'size' => '2.4 GB', 'status' => 'complete'],
        ['label' => 'Before migration', 'when' => 'Yesterday', 'size' => '2.3 GB', 'status' => 'complete'],
        ['label' => 'Manual snapshot', 'when' => 'In progress', 'size' => '1.1 GB', 'status' => 'running'],
    ],
    'files' => [
        ['path' => 'data/ModConfig/', 'kind' => 'folder'],
        ['path' => 'data/ModConfig/primitivesurvival.json', 'kind' => 'file', 'preview' => "{\n  \"TrapChance\": 0.35,\n  \"EnableSnakes\": true\n}"],
        ['path' => 'data/Playerdata/', 'kind' => 'folder'],
        ['path' => 'data/Saves/ember-hollow-main.vcdbs', 'kind' => 'file'],
        ['path' => 'data/serverconfig.json', 'kind' => 'file', 'preview' => "{\n  \"ServerName\": \"Ember Hollow\",\n  \"MaxClients\": 12,\n  \"Port\": 42420\n}"],
    ],
    'console_lines' => [
        ['level' => 'info', 'text' => '[Server] Dedicated server now running on port 42420'],
        ['level' => 'info', 'text' => '[Server] World loaded: ember-hollow-main'],
        ['level' => 'chat', 'text' => '<NorthwindAlex> anyone around for copper?'],
        ['level' => 'chat', 'text' => '<Mira> heading back from the ruins now'],
        ['level' => 'info', 'text' => '[ModDB] BetterRuins update available (0.5.9)'],
        ['level' => 'warn', 'text' => '[Backup] Manual snapshot started'],
    ],
    'pairing' => [
        'daemon_name' => 'basement-box',
        'token_preview' => null,
    ],
    'attribution' => [
        'name' => 'Voltaic Hosting',
        'url' => 'https://voltaic.host',
        'text' => 'Panel built by',
        'icon' => 'images/partners/voltaic/favicon-32.png',
    ],
];
